### ISSUE TITLE
Branch is not detected

### ISSUE THREAD

**Issue by oliverkuntze** [ilovemilk/semver-git-plugin#15]
Hi & thanks for the great plugin!
While on master I haven't had any problems so far.
Now I am on a gitlab feature branch named  abcd-10847-abcde-abc and the plugin returns 
Branch name: 
Branch group: 
Branch id: 
git rev-parse --abbrev-ref HEAD gives the correct name.
Any idea why?
Cheers
Oliver

**Comment by ilovemilk** [comment]
Hi oliverkuntze,

I found this bug a few days ago it resulted from a buggy regex. It should be fixed with version 2.0.2.

I would be happy if you could verify!

Best regards
Matthias

**Comment by oliverkuntze** [comment]
Cool. Thanks Matthias! Will test once 2.0.2 is out.
Cheers
Oliver

**Comment by ilovemilk** [comment]
You can find it [here](https://plugins.gradle.org/plugin/io.wusa.semver-git-plugin) or now under releases here on github.

Best regards
Matthias
