### ISSUE TITLE
io.wusa.Info cannot be cast to java.lang.String

### ISSUE THREAD

**Issue by terryf82** [ilovemilk/semver-git-plugin#16]
When running this plugin as part of a jib build in github Actions, the following error is thrown when trying to use the `semver.info` value as an image tag:

```
Execution failed for task ':jib'.
Task ':jib' is not up-to-date because:
> io.wusa.Info cannot be cast to java.lang.String
  Task has not declared any outputs despite executing actions.
```

Relevant section of build.gradle:
```
to {
    image = "....dkr.ecr.us-east-1.amazonaws.com/repo/image-name"
    tags = [semver.info]
}
```

semver.info can be seen when debugging locally:
```
task debugSemver {
    doLast {
        println semver.info
    }
}
```
output is `0.1.0+build.64.sha.0a28689-SNAPSHOT`

Any suggestions appreciated, thanks.

**Comment by ilovemilk** [comment]
Hi Terryf82,

Sadly I only had a kotlin script based gradle project laying around to check the problem but for me this works fine:

build.gradle.kts
```
jib {
    to {
        image = "test"
        tags = mutableSetOf(semver.info.toString())
    }
}
```

So did you try to just add `toString()`? E.g.

```
to {
    image = "....dkr.ecr.us-east-1.amazonaws.com/repo/image-name"
    tags = [semver.info.toString()]
}
```
Best regards
Matthias
