### ISSUE TITLE
Ability to set snaphshotSuffix per branch

### ISSUE THREAD

**Issue by pniederlag** [ilovemilk/semver-git-plugin#27]
I'd like to have the _release/x.y.z_ branches to not contain the snapshotSuffix. To solve this I now add the snapshotSuffix into my branch formatters as string. Would be nice if there was a more generic way to enable the snapshotSuffix per branch.

maybe [https://github.com/ilovemilk/semver-git-plugin/blob/master/src/main/kotlin/io/wusa/extension/Branch.kt](https://github.com/ilovemilk/semver-git-plugin/blob/master/src/main/kotlin/io/wusa/extension/Branch.kt) could be extended by adding a _isReleaseProperty_ ?

What do you think?

Thx and greets,
Peter

**Comment by ilovemilk** [comment]
Afaik every build that is not a release build is a snapshot build and should have a snapshot suffix.
Only builds which have an annotated git tag with a semantic version are releases. Therefore any other build should be snapshot builds.

How do you use the release branch? I can't think of a case where every build on a branch is release and should not have a snapshot suffix. I would use the release branch as a branch for an upcoming release to improve the quality and stability of the release. Hence, I would have many snapshot builds on this branch before releasing the final version.

**Comment by pniederlag** [comment]
Thx for your feedback. In general this is all true. However we are building java artifacts into an artifactory repository. By design this repository has different handling for snapshot and release versions.

The repository can hold multiple versions for the very same snapshotversion. When requesting a snapshot-version from the repository it will always give you the most recent snapshot.
For a release you can only have one single artifact. It is not possible to attach another build into the release version.

We like to use the release/* branch for starting to push real, unique releases, without having to add annotated tags. Any build on the release/* branch is considered an rc.${buildNumber) release but does NOT require a tag to be set. Any build on the release/* branch is NOT considered snapshot anymore. the release/* branch has the purpose to pave the way from SNAPSHOT on develop to finally setting the tag and merging to master (gitflow). And we don't want to pollute our git with .rc.x like tags.

SNAPSHOT (running of develop)

- 2.1.0-SNAPSHOT
  - 2.1.0-develop-23.sha.7ce0af136
  - 2.1.0-develop-24.sha.7380913f5
  - 2.1.0-develop-25.sha.e01f7e7
  [- 2.1.0-develop-${buildNumber}.sha.${shortcommit}]

RELEASE-rc  (running of release/*)

- 2.1.0-rc.${buildNumber}
  - 2.1.0-rc-${buildNumber}.sha.7ce0af136

RELEASE (annotated tag)
- 2.1.0
  - 2.1.0-${buildNumber}.sha.7ce0af136

Hope I could explain the reasoning why we'd like to be able to adapt '-SNAPSHOT' on a "by branch" base.

**Comment by ilovemilk** [comment]
Thanks for the explanation that helped a lot. Now that you mentioned it I observed a smiliar problem in one of my repositories which was full of tags because of many prereleases.

This sounds like a reasonable use case to introduce a branch specific snapshot suffix.
I think it would be good to keep the global snapshot suffix but also enabling the user to override it for specific branches.

**Comment by ilovemilk** [comment]
I started implementing this feature at the weekend see PR #32.
