### ISSUE TITLE
Question about branches var

### ISSUE THREAD

**Issue by Bittuw** [ilovemilk/semver-git-plugin#31]
Can you explain how increment works? I just copy your example and change `incrementer` to "MINOR_INCREMENTER", but there is nothing happened.

**Comment by ilovemilk** [comment]
HI Bittuw,

Do you still need help?

Nevertheless, if a branch has a MINOR_INCREMENTER, every commit should increse the minor version by one e.g. 2.0.0 -> new commit -> 2.1.0 -> new commit -> 2.2.0.

I hope this helps!

Matthias

**Comment by Bittuw** [comment]
Thanks for the explanation
