### ISSUE TITLE
Configuration Fails on formatter

### ISSUE THREAD

**Issue by bellini-ea** [ilovemilk/semver-git-plugin#33]
Hello,
Essentially copy and pasting from the readme

**When running "build" on the commandline, fails with the following:**
```Script compilation error:

  Line 26:             formatter = { "${semver.info.version.major}.${semver.info.version.minor}.${semver.info.version.patch}+build.${semver.info.count}.sha.${semver.info.shortCommit}" }
                                   ^ Type mismatch: inferred type is () -> String but Transformer<Any, Info> was expected
```

**Comment by ilovemilk** [comment]
Do you use groovy or kotlin for you build.gradle?

**Comment by bellini-ea** [comment]
I'm using Kotlin DLS for the build.gradle.kts.  Gradle version is 6.2.2 and 6.3.0 depending which project I'm on.

**Comment by ilovemilk** [comment]
For Kotlin its:

```
branch {
     regex = ".+"
     incrementer = "MINOR_INCREMENTER"
     formatter = Transformer<Any, Info>{ info:Info -> "${info.version.major}.${info.version.minor}.${info.version.patch}" }
}
```
The code you postet was for groovy.

**Comment by bellini-ea** [comment]
The code I pasted was from the readme.md for this plugin.  Using the Transformer solved it for me.  Thanks.

**Comment by ilovemilk** [comment]
All the examples in the readme.md are only for groovy. Maybe I should add examples for kotlin, too.
