### ISSUE TITLE
Branch Not Detected Propertly

### ISSUE THREAD

**Issue by bellini-ea** [ilovemilk/semver-git-plugin#35]
A branch named `feature/bellini/test-branch-version` does not get picked up by regex of `feature.+`.  `gradlew showInfo` does not show the branch name properly in the `Branch name:` and `Branch group:` sections (see the output).  The `feature/` is cut off/omitted which is most likely why the regex is not picking up properly.  Result is my format is used and so the default kicks in.

### gradlew showInfo 
Command line start has the git branch I am on in these screen shots.
Notice the `Version` format is the default (has `.build` in it) which means the regex was not picked up/used which is due to the plugin not using the full branch name.
![image](https://user-images.githubusercontent.com/46908694/87384279-324a3100-c550-11ea-8f9b-d7e4a167c01b.png)

### Configuration
![image](https://user-images.githubusercontent.com/46908694/87384375-69204700-c550-11ea-8ac5-e9e48acd398b.png)

### Test with feature/test-branch-version branch name
When trying a branch with the `bellini` part removed things work properly (i.e. `feature/test-branch-version`)
![image](https://user-images.githubusercontent.com/46908694/87384437-9bca3f80-c550-11ea-9480-ee7bc940acfe.png)

**Comment by ilovemilk** [comment]
Thanks for reporting this issue.

Will be fixed with the linked PR.

**Comment by bellini-ea** [comment]
Thanks so much.  Very much appreciate your quickness and your test cases.
