### ISSUE TITLE
Tags read as tied to Branches (?)

### ISSUE THREAD

**Issue by bellini-ea** [ilovemilk/semver-git-plugin#38]
I'm seeing that after tagging a release on the release branch as say 1.0.0, switching to master and running showInfo results in 1.0.0+pre-<commit> where I am expecting it to be 1.1.0+pre-<commit> (I have minor increment set for master).

### Full steps and configuration follow:
![image](https://user-images.githubusercontent.com/46908694/87582090-bf939f80-c68e-11ea-85cc-84f8260bf8b8.png)
![image](https://user-images.githubusercontent.com/46908694/87582143-d33f0600-c68e-11ea-861e-cd76a994c4e3.png)
![image](https://user-images.githubusercontent.com/46908694/87582236-fb2e6980-c68e-11ea-9244-7e405718e8ea.png)

### Configuration
![image](https://user-images.githubusercontent.com/46908694/87582296-113c2a00-c68f-11ea-84f4-d6d07761f7a1.png)

**Comment by ilovemilk** [comment]
Okay, hopefully I can explain the problem in way it's understandable.

If you think of the git tree of your branches:

```
release     TAG 1.0.0
             |
master ------o <- you are here
           |
feature ----
```

If you are on the master branch it only traverse the master branch and all branches merged into the master branch and takes the tags from there. In this example: master and feature. So it doesn't find the tag on the release branch.

If you would merge back the release into the master after the tag it would like this:

```
release       TAG 1.0.0
              |  |
master ----------o <- you are here  
              |
feature -------
```

Now it would traverse master, release and feature for tags and would find the tag 1.0.0.

For a more detailed explanation see: https://git-scm.com/docs/git-describe

I hope this is understandable! :)
