### ISSUE TITLE
Tag Not Picked Up Due to Incorrect Branch Name(?)

### ISSUE THREAD

**Issue by bellini-ea** [ilovemilk/semver-git-plugin#39]
Thanks for all the help so far.  I'm seeing even though I have a tag of 6.0.0, `showVersion` or `showInfo` shows 5.3.0+pre-<commit>-SNAPSHOT.  Trying to understand why its not 6.0.0 for the version on the release branch at least.  For some reason, on my release line, **showInfo** does not show the branch name?

I have a master and release line.  

### **Master** Line  Tags
```
C:\dev\gitlab.ea\ppp\ppp-common (master -> origin)
λ git tag -l
5.2.0
5.3.0
6.0.0
```
### **Release** Line Tags
```
C:\dev\gitlab.ea\ppp\ppp-common (release -> origin)
λ git tag -l
5.2.0
5.3.0
6.0.0
```
### **Master** showVersion Output
```
C:\dev\gitlab.ea\ppp\ppp-common (master -> origin)
λ gradlew showInfo

> Task :exception-common:showInfo
Branch name: master
Branch group: master
Branch id: master
Commit: f19f90c7f9e3e5883cad85d209d76832d254087f
Short commit: f19f90c
Tag: none
Last tag: 5.2.0-14-gf19f90c
Dirty: false
Version: 5.3.0+pre-f19f90c-SNAPSHOT
Version major: 5
Version minor: 3
Version patch: 0
Version pre release: none
```

### **Release** showVersion Output
Notice the Branch name here for the release line is not **release**.
```
C:\dev\gitlab.ea\ppp\ppp-common (release -> origin)
λ gradlew showInfo

> Task :exception-common:showInfo
Branch name: f19f90c7f9e3e5883cad85d209d76832d254087f
Branch group: f19f90c7f9e3e5883cad85d209d76832d254087f
Branch id: f19f90c7f9e3e5883cad85d209d76832d254087f
Commit: 9f5db437d49ba6ca314e36ced39cc7f3f2856086
Short commit: 9f5db43
Tag: none
Last tag: 5.2.0-11-g9f5db43
Dirty: false
Version: 5.3.0+pre-9f5db43-SNAPSHOT
Version major: 5
Version minor: 3
Version patch: 0
Version pre release: none
Version build: none
```

### Configuration (using Kotlin DSL)
```
semver {
        val versionFormatPreRelease = Transformer<Any, io.wusa.Info>{ "${semverBase}+pre-${semver.info.shortCommit}" }
        val versionFormatRelease = Transformer<Any, io.wusa.Info>{ semverBase }

        snapshotSuffix = "SNAPSHOT"
        dirtyMarker = "dirty"
        initialVersion = "6.0.0"
        tagPrefix = ""

        branches {
            branch {
                regex = "master"
                incrementer = "MINOR_INCREMENTER"
                formatter = versionFormatPreRelease
            }
            branch {
                regex = "release"
                incrementer = "MINOR_INCREMENTER"
                formatter = versionFormatRelease
            }
            branch {
                regex = "feature.+"
                incrementer = "MINOR_INCREMENTER"
                formatter = versionFormatPreRelease
            }
            branch {
                regex = "patch.+"
                incrementer = "PATCH_INCREMENTER"
                formatter = versionFormatRelease
            }
            // This is the catch all if we have a branch not conforming to the above bramches
            branch {
                regex = ".+"
                incrementer = "MINOR_INCREMENTER"
                formatter = versionFormatPreRelease
            }
        }
    }
```

**Comment by bellini-ea** [comment]
Just wanted to ping on this to get some thoughts on what might be happening.  Appreciate the help.

**Comment by bellini-ea** [comment]
I believe the regex isn't working as expected in the GitService.kt  filterCurrentBranch() method.

I hacked the unit test to point to my local as per the above and it shows the branch name as the long uuid like value.

Running `git branch --all --verbose --no-abbrev --contains` like the code, my output is like so:

```
git branch --all --verbose --no-abbrev --contains

  feature/bellini/default-version                  57e0ca224f386442b692c982f90ffdcb38af6762 [gone] Hardcode the version.
  master                                           268f7d96fc3def7da4ae14e94e66e9136d0ec963 Merge branch 'feature/bellini/default-version' into 'master'
* release                                          9f5db437d49ba6ca314e36ced39cc7f3f2856086 Merge branch 'master' into release
  remotes/origin/feature/personA/broker-exception 01c3b975dfd04994e7ce1fdba9dce433bc9d10f2 Update BrokerException model
  remotes/origin/feature/personB/overrides-fun       48de23188cb191f7686978e9c55a6593303e118b overrides fun
  remotes/origin/master                            268f7d96fc3def7da4ae14e94e66e9136d0ec963 Merge branch 'feature/bellini/default-version' into 'master'
  remotes/origin/release                           9f5db437d49ba6ca314e36ced39cc7f3f2856086 Merge branch 'master' into release
```

where `57e0ca224f386442b692c982f90ffdcb38af6762` is returned by filterCurrentBranch()

**Comment by bellini-ea** [comment]
I tried a each version back till 2.2.0.  2.2.3 has the issue as above.  however all the other v ersion like 2.2.0, 2.2.1, show the wrong branch name.  

For example, I'm on a release branch and run showInfo where it ends up saying the branch is some other name.  

```
Branch name: bellini/default-version
Branch group: bellini
Branch id: bellini-default-version
Commit: 9f5db437d49ba6ca314e36ced39cc7f3f2856086
Short commit: 9f5db43
Tag: none
Last tag: 5.2.0-11-g9f5db43-dirty
Dirty: true
Version: 5.3.0+pre-9f5db43-dirty-SNAPSHOT
Version major: 5
Version minor: 3
Version patch: 0
Version pre release: none
Version build: none
```

Where you can see the branch I ran the above on here:
```
C:\dev\gitlab.ea\poutine\poutine-common (release -> origin)
λ git status
On branch release
Your branch is up to date with 'origin/release'.

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
        modified:   build.gradle.kts

no changes added to commit (use "git add" and/or "git commit -a")
```

**Comment by bellini-ea** [comment]
I have a fix that seems to be working however I am unable to push an MR.  Says access denied so not sure if its me or I need to be added to push an MR.

**Comment by ilovemilk** [comment]
Hi bellini-ea,

sorry for my late response.

Thanks for digging into this problem. You have to fork the repository create a branch with your fix and the create a MR to this repository!

I took a short look at the `filterCurrentBranch()` method:
The problem here is that it takes the first branch of `git branch --all --verbose --no-abbrev --contains` in your case this `feature/bellini/default-version` and not `release` but release is the active branch and not the `feature/bellini/default-version` branch. Therefore it should take the branch with the asterisk (*) infront.

If you have found a fix for this issue I would be very happy and thankful if you create a MR! :)

Is the `6.0.0` tag an annotated tag? Can you execute `git describe --dirty --abbrev=7 --match *` and post the result?

**Comment by bellini-ea** [comment]
PR is here.  Hopefully I did this correctly (too much corporate life :) )
https://github.com/ilovemilk/semver-git-plugin/pull/42

In regards to the tags, here is the result of the command:
```
C:\dev\gitlab.ea\poutine\poutine-common (release -> origin)
λ git describe --dirty --abbrev=7 --match *
5.2.0-11-g9f5db43-dirty
```

**Comment by ilovemilk** [comment]
Thanks you PR looks good! :)

Okay now we know it's not a problem with the plugin itself because git does also report the wrong tag 5.2.0 instead of 6.0.0.
Possible problems: 
* The git tag is not reachable from the release branch? Is it directly on the release branch?
* The tag is not annotated and therefore not detected by git describe?

**Comment by bellini-ea** [comment]
Okay so interesting stuff here.

On my release branch
```
> Task :blah-sub-project:showInfo
Branch name: 57e0ca224f386442b692c982f90ffdcb38af6762
Branch group: 57e0ca224f386442b692c982f90ffdcb38af6762
Branch id: 57e0ca224f386442b692c982f90ffdcb38af6762
Commit: 9f5db437d49ba6ca314e36ced39cc7f3f2856086
Short commit: 9f5db43
Tag: none
Last tag: 5.2.0-11-g9f5db43
Dirty: false
Version: 5.3.0+pre-9f5db43-SNAPSHOT
Version major: 5
Version minor: 3
Version patch: 0
Version pre release: none
Version build: none
```

Checking if the tag is annotated (if annotated, it will say `tag`)
```
C:\dev\gitlab.ea\ppp\ppp-common (release -> origin)
λ git cat-file -t 6.0.0
commit
```

Delete and re-add the tag and check that its annotated
```
C:\dev\gitlab.ea\ppp\ppp-common (release -> origin)
λ git tag
5.2.0
5.3.0
6.0.0

C:\dev\gitlab.ea\ppp\ppp-common (release -> origin)
λ git tag -d 6.0.0
Deleted tag '6.0.0' (was 9f5db43)

C:\dev\gitlab.ea\ppp\ppp-common (release -> origin)
λ git tag
5.2.0
5.3.0

C:\dev\gitlab.ea\ppp\ppp-common (release -> origin)
λ git tag -a 6.0.0 9f5db4 -m "6.0.0"

C:\dev\gitlab.ea\ppp\ppp-common (release -> origin)
λ git cat-file -t 6.0.0
tag
```
Running git cat-file again shows its no longer annotated
```
C:\dev\gitlab.ea\ppp\ppp-common (release -> origin)
λ git cat-file -t 6.0.0
commit
```

What I found was GitKraken client when open changes the tag to NOT be annotated.  So when the tag is annotated the semver-git-plugin is doing what we expect.

If we add --tags to git describe, it seems like it will work regardless of annotation.  Thoughts?

```
C:\dev\gitlab.ea\poutine\poutine-common (release -> origin)
λ git tag -a 6.0.0 9f5db4 -m "6.0.0"

C:\dev\gitlab.ea\poutine\poutine-common (release -> origin)
λ git cat-file -t 6.0.0
tag

C:\dev\gitlab.ea\poutine\poutine-common (release -> origin)
λ git describe
6.0.0

C:\dev\gitlab.ea\poutine\poutine-common (release -> origin)
λ git describe
6.0.0
```

Remove the annotation from the tag

```
C:\dev\gitlab.ea\poutine\poutine-common (release -> origin)
λ git describe
5.2.0-11-g9f5db43
```

Using --tags on git describe
```
C:\dev\gitlab.ea\poutine\poutine-common (release -> origin)
λ git describe --tags
6.0.0
```

**Comment by ilovemilk** [comment]
Good find! The reason why I choose annotated tags over lightweicht tags ist that they store more information which can be quite helpful but we could add a flag to the configuration to include lightweight tags.
E.g.
`includeLeightweightTags = true`

What do you think?

**Comment by bellini-ea** [comment]
Was there anything that the plugin would lose today by using light weight tags if we have this option?  It can still perform all its tasks I assume?

Assuming I understand correctly, I would suggest the name be,
useLightWeightTags = true | false

or make it an enum like

enableTagType = "annotated" | "light" | ....

**Comment by ilovemilk** [comment]
The plugin would loose nothing. It would work in the same way but I normally use lightweight tags in my repos for non-release tags to mark old ideas or approaches.

I like the idea with the enum the values would be annotated, lightweight and both. Or is there something I missed?

**Comment by bellini-ea** [comment]
Yah I'm easy with this one.  Is this something you can add and release with my fix for the current branch as well?

**Comment by ilovemilk** [comment]
Sure I will do this. Sadly, I can add this feature not earlier than thuesday next week.

**Comment by bellini-ea** [comment]
Okay, thank you.  How about the MR https://github.com/ilovemilk/semver-git-plugin/pull/42 ?  Can that go in now?

**Comment by bellini-ea** [comment]
Opened up an MR with a way to do it in case it helps and matches how you would like it done:
https://github.com/ilovemilk/semver-git-plugin/pull/43

**Comment by ilovemilk** [comment]
Merging requests is no problem. I just don't have access to my PC to edit any code. If you bump the version to 2.2.4 and update the changelog in #42 I can also release it.

**Comment by bellini-ea** [comment]
Made all the changes and test it locally against my project.  I'm seeing the branch name and the tag all come out properly.

**Comment by ilovemilk** [comment]
Sorry for the delay. I released the your fix with version 2.2.4. The feature with lightweight and annotated tags will follow soon.

**Comment by pantovad** [comment]
Unfortunately the new implementation of getCurrentBranch relying on "git branch --show-current" makes the plugin useless on Jenkins or wherever detached HEAD checkouts are typically done.  --show-current gives no result for detached HEAD state  (from the git doc):

--show-current
           Print the name of the current branch. In detached HEAD state, nothing is printed.

**Comment by ilovemilk** [comment]
Thanks for reporting back. I will add a test and fix this as soon as possible.

**Comment by ilovemilk** [comment]
The linked pull request should fix the detached HEAD problem if you could take a look that would be amazing!
