### ISSUE TITLE
CONVENTIONAL_COMMITS_INCREMENTER not working

### ISSUE THREAD

**Issue by supertote** [ilovemilk/semver-git-plugin#40]
When using CONVENTIONAL_COMMITS_INCREMENTER, the version number stays at the version in the last annotated tag.

It seems due to a typo in method GitService.getCommitsSinceLastTag which uses git log option "--online" instead of "--oneline".

**Comment by ilovemilk** [comment]
Hi supertote,

Thanks for reporting this bug and the solution! :) I will add a test and release a new version with a fix.

**Comment by ilovemilk** [comment]
Fixed with version 2.2.4.
