### ISSUE TITLE
Replace selection of the incrementer by string with enum

### ISSUE THREAD

**Issue by ilovemilk** [ilovemilk/semver-git-plugin#45]
The selection of the incrementer is currently done by a string variable. To reduce the potential of typos replace it with an enum.

**Comment by smerschjohann** [comment]
It would be nice to be able to pass a function as well. In that way, one can define a custom incrementer.

**Comment by ilovemilk** [comment]
Similar to the formatter I could add the possibility to use a transformer from Info to String. What do you think?

**Comment by smerschjohann** [comment]
sounds good, in that way everyone can change it to their liking
