### ISSUE TITLE
Support Windows, older Git-Versions and CI/CD

### ISSUE THREAD

**Issue by smerschjohann** [ilovemilk/semver-git-plugin#46]
First: This gradle plugin looks very nice, thanks for it.

The command `git branch --show-current` is a quiet new feature and is not present in git < 2.22.0. So it would be safer to use `git rev-parse --abbrev-ref HEAD` instead.

Furthermore, the version cannot be determined in the git log query on windows, since it uses SH features, it would be better to split it in two seperate commands instead of relying on the bash.

And last but not least: On some CI systems, instead of the branch the commit itself is checked out, which results in a detached HEAD. For this case the getBranch() command will fail. It would be nice, if there is a feature, that allows to set the branch externally, as the branch is passed to the CI pipeline via environment variables in most cases.

**Comment by ilovemilk** [comment]
Maybe we should replace the usage of the git binary with a git java implementation like jgit, as mentioned in #44.
This would solve the feature and os problem.

Regarding the branch: You mean like a configuration variable `currentBranch` which can be set to the external branch and if not it takes the default strategy?

**Comment by smerschjohann** [comment]
Yes, JGit would be another good option, but I don't know if everything is possible with that implementation.

Regaring the Branch info: I think we should have different options here: directly setting the "currentBranch" as well as a configuration option to set the environment variable in which the branch is set. E.g. gitlab CI stores the branch information in the environment variable "CI_COMMIT_BRANCH". If we are able to configure it by a setting like branchEnv = "CI_COMMIT_BRANCH" that would be nice.

**Comment by ilovemilk** [comment]
I replaced the `git branch --show-current` command with `git log` and some RegEx parsing this should improve the Git compatibility.
