### ISSUE TITLE
CONVENTIONAL_COMMITS_INCREMENTER not incrementing version

### ISSUE THREAD

**Issue by Denis220795** [ilovemilk/semver-git-plugin#47]
Hello, thank you for this cool plugin, that's really useful! We have tried to use CONVENTIONAL_COMMITS_INCREMENTER but for some reasons version stay the same as latest available lightweight tag.

Version of the plugin: 2.3.0

Configuration of the plugin:
```
semver {
    snapshotSuffix = "SNAPSHOT" // (default) appended if the commit is without a release tag
    dirtyMarker = "dirty" // (default) appended if the are uncommitted changes
    initialVersion = "0.1.0" // (default) initial version in semantic versioning
    tagPrefix = "" // (default) each project can have its own tags identified by a unique prefix.
    tagType = TagType.LIGHTWEIGHT // (default) options are Annotated or Lightweight
    branches { // list of branch configurations
        branch {
            incrementer = "CONVENTIONAL_COMMITS_INCREMENTER" // (default) version incrementer
            formatter = { "${semver.info.version.major}.${semver.info.version.minor}.${semver.info.version.patch}" } // (default) version formatting closure
            regex = ".+" // regex for the branch you want to configure, put this one last
        }
    }
}
```

commit examples:

```
$ git log --oneline $(git describe --tags --abbrev=0 @^)..@
685f852 (HEAD -> feature/JiraIssue-11111_add_semver_plugin) feat: added semver plugin incrementer parameter
7c03cdd feat: added semver plugin incrementer parameter
f45e853 feat: added semver plugin incrementer parameter
```

These commits should match regex configured here:
https://github.com/ilovemilk/semver-git-plugin/blob/master/src/main/kotlin/io/wusa/incrementer/ConventionalCommitsIncrementer.kt#L13

Latest available tag before these 3 commits is 2.0.42 and after running e.g showVersion command it shows same version (but should show version with incrementing minor version - 2.1.0):

```
> Task :showInfo
Branch name: feature/JiraIssue-11111_add_semver_plugin
Branch group: feature
Branch id: feature/JiraIssue-11111_add_semver_plugin
Commit: 7b398669d1491f3cf2e1d6e17e4a8dd608c1ed42
Short commit: 7b39866
Tag: none
Last tag: 2.0.42-3-g7b39866
Dirty: false
Version: 2.0.42-SNAPSHOT
Version major: 2
Version minor: 0
Version patch: 42
Version pre release: none
Version build: none
```

Minor/Major/Patch incrementing working well. Am I doing smth wrong here or this is a bug?

Possibly related to issue https://github.com/ilovemilk/semver-git-plugin/issues/40

**Comment by ilovemilk** [comment]
Hi, thanks for reporting this issue. I try to look into this issue today.

**Comment by ilovemilk** [comment]
Which operating system do you use?

**Comment by Denis220795** [comment]
I've tried this on Windows in both GitBash and Regular CMD console.

**Comment by ilovemilk** [comment]
Okay then I found the problem! :) I will release a new version with a fix.
