### ISSUE TITLE
Extension with name 'semver' does not exist.

### ISSUE THREAD

**Issue by Max-Levitskiy** [ilovemilk/semver-git-plugin#53]
I have a kotlin dsl. 
I have this code related with plugin: 
`
plugins {
    id("io.wusa.semver-git-plugin") version "2.3.0"
}
allprojects {
    version = semver.info
}
`

And have a run result:

> ❯ ./gradlew build                                                                                                                                       
> FAILURE: Build failed with an exception.
> * Where:
> Build file '/home/max/git/cloud-resource-dashboard/build.gradle.kts' line: 28
> * What went wrong:
> Extension with name 'semver' does not exist. Currently registered extension names: [ext]

**Comment by ilovemilk** [comment]
Which Gradle version do you use?

**Comment by ilovemilk** [comment]
I'm closing this issue because it has been inactive for over one month now.
