### ISSUE TITLE
Make GitCommandRunner Configurable

### ISSUE THREAD

**Issue by saltwaterburning** [ilovemilk/semver-git-plugin#55]
Our builds are failing with occasional time-out errors.  Can the Git command time-out be made longer or configurable?

* What went wrong:
Execution failed for task ':compileJava'.
> Could not resolve all dependencies for configuration ':detachedConfiguration87'.
   > Execution timed out: io.wusa.GitCommandRunner$Companion@64bc99d9

**Comment by saltwaterburning** [comment]
Never mind! This plugin hangs indefinitely on projects with very large number of tags. We switched to a more reliable semver plugin.

**Comment by ilovemilk** [comment]
Hi,

can you give me some info on how many tags you have in your repository? And to which plugin you switched?

Would be great so I could improve this! 👍 

Thanks

**Comment by ilovemilk** [comment]
The problem with the timeout has been fixed. Closing this issue now!
