### ISSUE TITLE
CONVENTIONAL_COMMITS_INCREMENTER not incrementing version

### ISSUE THREAD

**Issue by supertote** [ilovemilk/semver-git-plugin#56]
Hi,

I already reported issue #40 about conventional commit incrementer but was unable to test the fix you provided until today.
Unfortunately the fix was not enough and the version number is not incrementing.
After looking at the code it seems that:
1. your regexp for testing the content of the commit messages starts with **[0-9a-f]{7}** for the abbreviated commit sha but when I do **git log --oneline** (with git 2.28.0) the abbreviated sha is on 8 characters, not 7
2. if the commit message contains blank lines (as specified in the [Conventional Commit](https://www.conventionalcommits.org/) specification) then only the first line will be reported by **git log --oneline** so any trailing **BREAKING CHANGE** line will not appear
3. **git log --oneline** will also report refs between the abbreviated sha and the commit message preventing the detection of **feat** or **fix**, e.g.:

> 31086b72 **(HEAD -> #62-upgrade-semver-git-plugin)** feat: moving to semver-git-plugin 2.3.1

4. **BREAKING CHANGE** (when reported in the line) will most likely not appear just after the abbreviated sha and will never be detected

Additionally, you are not testing for a **!** character following **feat** or **fix** to indicate a breaking change as specified in the [Conventional Commit](https://www.conventionalcommits.org/) specification.

What I suggest is the following:
1. replace **git log --oneline** with **git log "--pretty=format:%s %(trailers:separator=%x2c)"**: this will eliminate the abbreviated sha and include the first line of the commit message plus any trailing line starting with **\<some keyword\>:** and will therefore include **BREAKING CHANGE** whether there are blank lines or not in the message (as long as it is followed by a colon)
2. in method **ConventionalCommitsIncrementer.increment** do the following:
```kotlin
val OPTIONAL_SCOPE  = "(\\(.*?\\))?"
val FEAT            = "^feat$OPTIONAL_SCOPE"
val FIX             = "^fix$OPTIONAL_SCOPE"
val BREAKING_CHANGE = "\\bBREAKING CHANGE\\b:"

listOfCommits.forEach {
    when {
        it.contains("$FEAT!:".toRegex())       -> major += 1
        it.contains("$FIX!:".toRegex())        -> major += 1
        it.contains(BREAKING_CHANGE.toRegex()) -> major += 1
        it.contains("$FEAT:".toRegex())        -> minor += 1
        it.contains("$FIX:".toRegex())         -> patch += 1
    }
}
```

**Comment by ilovemilk** [comment]
Thanks for your extremly well documented issue! I will extend the tests and add your suggested changes.
