### ISSUE TITLE
CONVENTIONAL_COMMITS_INCREMENTER not working in dirty tree

### ISSUE THREAD

**Issue by supertote** [ilovemilk/semver-git-plugin#59]
Hi,
Following fix of issue #56 we are almost getting there for CONVENTIONAL_COMMITS_INCREMENTER.
On a clean tree we get the correctly incremented version.
But unfortunately on a dirty tree the version number (major, minor, patch) is not incremented.
This is due to the fact that you are passing argument **--dirty** to the **git describe** command in method **GitService.getCommitsSinceLastTag**.
Just removing the argument should be enough to fix it.
But to handle correctly dirty trees, I would suggest to also initialize variable patch (in method **ConventionalCommitsIncrementer.increment**) to 1 if the tree is dirty.

**Comment by ilovemilk** [comment]
Thanks! I add a test and fix this immediatly.

**Comment by ilovemilk** [comment]
> But to handle correctly dirty trees, I would suggest to also initialize variable patch (in method ConventionalCommitsIncrementer.increment) to 1 if the tree is dirty.

So if we have a repository with a tag e.g. 1.0.0 and a dirty working tree we would get the version 1.0.1-dirty-SNAPSHOT?
"-dirty" because of the dirty working tree,
"-SNAPSHOT" because we are not on the clean 1.0.0 tag anymore.

**Comment by supertote** [comment]
Correct, except that in my case I use a formatter which omits **-dirty** so I would end up with **1.0.1-SNAPSHOT**.
