### ISSUE TITLE
Error getting branch if the repo is "grafted"

### ISSUE THREAD

**Issue by robertomoreno** [ilovemilk/semver-git-plugin#65]
### What's wrong

While developing a CI/CD workflow using Github Actions I noticed that the branch was not picked correctly and versions were mess up. After some debugging it was clear that the plugging was not properly getting the branch: `semver.info.branch.name` was empty and `semver.info` returns something completely unrelated to what was configured, though locally works fine.

### Further analysis

This is how plugin is fetching the branch name:

        private fun getCurrentBranch(project: Project): String {
            val head = GitCommandRunner.execute(project.projectDir, arrayOf("log", "-n", "1", "--pretty=%d", "HEAD"))
            return """\(HEAD -> (.*?)[,|)]""".toRegex().find(head)!!.groupValues[1]
        }

So if I run `git log -n 1 --pretty=%d HEAD` in my laptop I get `(HEAD -> release-workflows, origin/release-workflows)` but in github `(grafted, HEAD -> release-workflows, origin/release-workflows)` so the Regex does not match. This is happening for the most common checkout scenario

      steps:
         - uses: actions/checkout@v2
         - ....

So as fix suggestions:

- Improve Regex expression to match more complex cases
- Use other (and simpler) commands as `git rev-parse --abbrev-ref HEAD` or `git branch --show-current` which don't require regex expression

### Workaround for Github actions

By default, checkout action brings only the interesting commit (this is where the "grafted" is coming from), so we can configure it to bring all the history as

      - uses: actions/checkout@v2
        with:
          fetch-depth: 0 # workaround for grafted issue

This is far more inefficient but it works if the repos has a reasonable size.

**Comment by ilovemilk** [comment]
Hi Roberto,

thanks for this well documented issue.

I will do some testing this evening and start to fix this problem. Little remark here: I used `git branch --show-current` before but I decided to drop this because of requirement to be compatible with git version older than 2.20.0.

Matthias

**Comment by roberto-morenoperez** [comment]
Can confirm the fix. Thx for tackle this so fast :) !

**Comment by ilovemilk** [comment]
Thanks for the feedback :)
